# Generated by Django 4.1.5 on 2023-02-19 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='year_of_birth',
            field=models.IntegerField(null=True),
        ),
    ]
